#!/bin/bash -e

. ../version.sh

export PATH=$PATH:$PWD/depot_tools

XCFRAMEWORK=WebRTC.xcframework
XCFRAMEWORK_ZIP=$XCFRAMEWORK.zip

DEBUG_ARM64_OUT=$PWD/debug/arm64
DEBUG_XCFRAMEWORK_PATH=$PWD/debug/$XCFRAMEWORK

RELEASE_ARM64_OUT=$PWD/release/arm64
RELEASE_XCFRAMEWORK_PATH=$PWD/release/$XCFRAMEWORK
RELEASE_XCFRAMEWORK_ZIP_PATH=$PWD/release/$XCFRAMEWORK_ZIP
